### ISSUE TITLE
command steps is not complete with no docker

### ISSUE THREAD

**Issue by songyangsun** [DRTorresRuiz/ConcreteDamageDetection#2]
like split datasets operation,hope can update the complete command steps.

**Comment by DRTorresRuiz** [comment]
Hello @songyangsun, thank you for your comment and sorry for my late answer. I will update this repository asap. 

I have received several emails with the same questions, so for now, I write a couple of points here for the sake of reproducibility without docker:

- The [`concrete`](https://github.com/DRTorresRuiz/ConcreteDamageDetection/blob/84271c8a5c66edb4950f7c25a76cc7a69ee961e6/concrete/main.py#L66-L93) command has different options, one of them is [`concrete split`](https://github.com/DRTorresRuiz/ConcreteDamageDetection/blob/84271c8a5c66edb4950f7c25a76cc7a69ee961e6/concrete/main.py#L66-L93) that mainly calls this function [`split_data()`](https://github.com/DRTorresRuiz/ConcreteDamageDetection/blob/84271c8a5c66edb4950f7c25a76cc7a69ee961e6/concrete/cli/utils.py#L71-L142). I used the given default values to split (i.e., 0.7 train, 0.1 validation, 0.2 test).
- Besides, the `concrete` command also has the [`augment`](https://github.com/DRTorresRuiz/ConcreteDamageDetection/blob/84271c8a5c66edb4950f7c25a76cc7a69ee961e6/concrete/main.py#L95-L111) option, to augment the data using this [pipeline](https://github.com/DRTorresRuiz/ConcreteDamageDetection/blob/84271c8a5c66edb4950f7c25a76cc7a69ee961e6/concrete/cli/utils.py#L151-L160).
